from typing import Literal, Optional
from pydantic import BaseModel, Field, ConfigDict, field_validator

Category = Literal[
    "appliance_repair",
    "general_home_repair",
    "plumbing_repair",
    "electrical_repair",
    "hvac_maintenance",
]


class HomeDiyRepairQA(BaseModel):
    """
    7-field schema matching the project spec.
    id and category are pipeline-assigned metadata; LLM generation omits them.
    """
    model_config = ConfigDict(extra="forbid")

    # Core spec fields — generated by the LLM
    question:          str       = Field(min_length=10,  max_length=500)
    answer:            str       = Field(min_length=20,  max_length=5000)
    equipment_problem: str       = Field(min_length=5,   max_length=300)
    tools_required:    list[str] = Field(min_length=1,   max_length=20)
    steps:             list[str] = Field(min_length=3,   max_length=25)
    safety_info:       str       = Field(min_length=20,  max_length=1000)
    tips:              list[str] = Field(min_length=1,   max_length=10)

    # Pipeline metadata — assigned after generation, not LLM-generated
    id:       Optional[str]      = Field(default=None, pattern=r"^qa_\d+$")
    category: Optional[Category] = None

    @field_validator("tools_required", "steps", "tips")
    @classmethod
    def no_empty_items(cls, values):
        for value in values:
            if not value.strip():
                raise ValueError("List fields cannot contain empty strings")
        return values
